### ISSUE TITLE
Build with failed openui5_theme task incorrectly returning 0 as overall return code

### ISSUE THREAD

**Issue by cmastrandrea** [SAP/less-openui5#21]
OpenUI5 version: 1.54.4 (with less-openui5 0.5.2)

Browser/version (+device/version): N/A

Any other tested browsers/devices(OK/FAIL): N/A

URL (minimal example if possible):  N/A

User/password (if required and possible - do not post any confidential information here):  N/A

Steps to reproduce the problem: 
1.  In the rel-1.54.4 OpenUI5 source (although version of OpenUI5 doesn’t matter – just version of less-openui5), remove the @sapBrandColor: #000; line at the top of the src/sap.ui.core/src/sap/ui/core/themes/base/base.less file.
2. Run:  node_modules/.bin/grunt build

What is the expected result?  A failed build with a non-zero return code.

What happens instead?  A build showing errors with a zero return code.

Any other information? (attach screenshot if possible)
Here’s the build log:
$ node_modules/.bin/grunt build
Running "build" task

Running "lastchange" task
lastchange: 8c09ecea323ea8dbc75e919829ef9e0b3ea38c3a

Running "copy:test-target-testsuite" (copy) task
Created 2 directories, copied 8 files

Running "copy:src-target-sap.ui.core" (copy) task
Created 95 directories, copied 879 files

Running "copy:test-target-sap.ui.core" (copy) task
Created 847 directories, copied 2893 files

Running "openui5_theme:target-sap.ui.core" (openui5_theme) task
{ Error
    at new Parser (C:\temp\openui5\node_modules\less\lib\less\parser.js:333:27)
    at parserFactory (C:\temp\openui5\node_modules\less-openui5\lib\less\parser.js:28:15)
    at createParser (C:\temp\openui5\node_modules\less-openui5\lib\less\parser.js:51:9)
    at C:\temp\openui5\node_modules\less-openui5\lib\index.js:195:17
    at compile (C:\temp\openui5\node_modules\less-openui5\lib\index.js:175:10)

  type: 'Name',
  message: 'variable @sapBrandColor is undefined',
  filename: '/sap/ui/core/themes/base/global.less',
  index: 394,
  line: 13,
  callLine: NaN,
  callExtract: undefined,
  column: 13,
  extract:
   [ '',
     '@sapUiBrand: @sapBrandColor;',
     '@sapUiHighlight: @sapHighlightColor;' ] }
Task 'build' took 3ms
Task 'lastchange' took 65ms
Task 'copy:test-target-testsuite' took 41ms
Task 'copy:src-target-sap.ui.core' took 2815ms
Task 'copy:test-target-sap.ui.core' took 11053ms
Task 'loading grunt-openui5' took 172ms
Task 'openui5_theme:target-sap.ui.core' took 225ms
All tasks took 14374ms

jobrag@d10a007 MINGW64 /c/temp/openui5 (rel-1.54.4)
$ echo $?
0

**Comment by matz3** [comment]
Thanks for reporting 👍 Will be fixed with #22
