### ISSUE TITLE
NPM warn security issue

### ISSUE THREAD

**Issue by gaiawork** [SAP/less-openui5#25]
Hi,

When using less-openui5 dependency, a security issue raised:
_**npm WARN notice [SECURITY] mime has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.2.11 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.**_

To fix this issue the dependency of less should be updated to 3.x versions,
because less@3.0.0 uses mime@^1.4.1

Thanks,
Gaia

**Comment by matz3** [comment]
We are already aware of this vulnerability and are checking on how to solve it.
Unfortunately we can not update the `less` dependency to e.g. v3.0.0 because of incompatibilities and internal dependencies which all rely on less v1.6.3. Upgrading to less v3 will therefore take quite some time.

**Comment by vvopenka** [comment]
It seems that GitHub started running security checks centrally. We've just received a mail warning regarding this issue for our project:

> We found a vulnerable dependency in a repository you have security alert access to.
 SAP/openui5-suite
Known moderate severity security vulnerability detected in clean-css < 4.1.11defined in yarn.lock.
--
yarn.lock update suggested: clean-css ~> 4.1.11.

**Comment by flovogt** [comment]
Hi team,
would be nice to get the npm warnings away. 

Best Regards

**Comment by matz3** [comment]
Thanks for bringing this up. I will try to push this again, but as already stated in my [previous comment](https://github.com/SAP/less-openui5/issues/25#issuecomment-390175967), an update will be not straight forward as you might think.

However `clean-css` is only being used when you activate it with the `cleancss` option on the [`compiler` options](https://github.com/SAP/less-openui5#compiler) of this module, which is not done by default.
