### ISSUE TITLE
`font-face` declarations must not use CSS variables for the `src` attribute

### ISSUE THREAD

**Issue by petermuessig** [SAP/less-openui5#267]
As reported by Hira Kshetry in the OpenUI5 Slack: [https://openui5.slack.com/archives/C0A7MHSSJ/p1672783549112489](https://openui5.slack.com/archives/C0A7MHSSJ/p1672783549112489), Icon Fonts don't work when using CSS variables.

I remember we discussed in the past, that the `font-face` declaration don't support variables in the `src` attribute. In this case, we might exclude the `font-face` declarations from the replacement with the CSS variables, when using less variables inside and furthermore manifest the concrete property value. 

We should verify this part with the `font-face` and then adopt the plugin dependent on the result.

**Comment by i556484** [comment]
Related internal incident: 2270189546

**Comment by matz3** [comment]
Should be fixed via https://github.com/SAP/less-openui5/pull/257. Or is there something else not working?

**Comment by matz3** [comment]
Closing as it's already solved via https://github.com/SAP/less-openui5/pull/257
