### ISSUE TITLE
missing "file not found" check may leads to a crash in compile()

### ISSUE THREAD

**Issue by themasch** [SAP/less-openui5#66]
When there is a .theming file the ui5-tooling reads it and tries to compile all libs with all scopes using [compileWithScope ](https://github.com/SAP/less-openui5/blob/master/lib/index.js#L291) which reads library.source.less files of all scopes and [calls compile on them ](https://github.com/SAP/less-openui5/blob/master/lib/index.js#L295)

readFile() returns a `Promise<FileContentAndInfo | null>` but compile does not [handle the `null`-case ](https://github.com/SAP/less-openui5/blob/master/lib/index.js#L178) which leads to a `TypeError: Cannot read property 'path' of null` if the expected files does not exist. 

While I guess this file (sap/$lib/themes/$themename/library.source.less)  *should* exists to get the correct result, a better error message would be nice here. 

This does not happen in our case when there is no .theming file, I guess because the theme in question is only pulled because of this file.

**Comment by FreshHead** [comment]
Hello. 
Somehow I get this error message when theme folder and file "library.source.less" are actually exists.
![image](https://user-images.githubusercontent.com/5730634/74913570-fe6c4480-53d1-11ea-8f3a-e1452c913d9f.png)
If I remove or rename folder "sap_belize" than error will gone.
Just yesterday all worked normally and now this error =(
Please help me find where is the cause and what should I do. Cannot debug in web ide or does not understand how :/

**Comment by FreshHead** [comment]
Update: 
My lib was on "@openui5/sap.ui.core": "1.60.*", downgrade to "1.58.*" helps for now

**Comment by FreshHead** [comment]
Removing of "@openui5/themelib_sap_belize": "1.60.*" dependency completly from package.json fixing this issue for me. This is a very bad fix because I think I needed theme in dependencies
