### ISSUE TITLE
CSS calc() function output incorrect.

### ISSUE THREAD

**Issue by sgarland** [SAP/less-openui5#74]
calc() expressions (https://developer.mozilla.org/en-US/docs/Web/CSS/calc) that contain a mix of units which cannot be simplified are being incorrectly modified.

For instance this  .less input:
```
.percentMinusEm {
  width: calc(100%-1em);
}
```

Results in this CSS output:
```
.percentMinusEm {
  width: calc(99%);
}
```

I can see that this bug is not present in the latest version of `less` when I use the less compiler directly.
I see notice that code changes are required to update the version of the less dependency.

When this is fixed, grunt-openui5 will also need to be updated to reference the new version of less-openui5.

I thought I would check to see if I could use the NPM based tools (https://github.com/SAP/ui5-builder) as a workaround, but I can see that project also uses less-openui5, so it would also be affected by this issue.

**Comment by matz3** [comment]
Please see [my comment in another issue](https://github.com/SAP/less-openui5/issues/25#issuecomment-390175967), on why we currently can't upgrade the less dependency.
