### ISSUE TITLE
Break the dependency on LESS: accept as input parameter

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/less-openui5#81]
Dear devs,

I would like to bring you an important suggestion which will make your module more usable.

Currently you have a dependency on less version which is declared right in your module.

This makes automatically impossible using all new less features without forking this repo, and updating the dependency.

Instead I suggest to add an optional less parameter for the Builder instanse, which will accept any less instance.

For example in the current version of this module I was not able to use this rule:

```
@sapList_SelectionBackgroundColor: .table_row_selected[background-color];
```

where the original class we cannot modify as it's maintained by other team in our company. 

This is officially supported ( and even advised to use ) [feature](http://lesscss.org/features/#maps-feature)

Instead of trying to syncronize feature-by-feature your plugin my proposal will just break this dependency and make this module reusable for long time without need in maintenance

**Comment by ThePlenkov** [comment]
the idea is like this:

```
const less = require("less");

const less_ui5 = require("less-openui5");

... 

new Builder().build({less})

```

**Comment by ThePlenkov** [comment]
in this case I can control the version of less used in own project.

**Comment by matz3** [comment]
@ThePlenkov did you already have a look into the compatibility with different versions and the code of this project? Especially the [internal less plugins](https://github.com/SAP/less-openui5/tree/master/lib/plugin) require a specific API that has changed with less v2 / v3.

**Comment by ThePlenkov** [comment]
@matz3 no, I didn’t go so deep - just saw you just use less internally. It’s never late to implement compatibility check for lower versions. The whole idea - is not to restrict the actual version which is constantly updated with new features. So speaking in other words to have a plug-in for less, accepting less as a context

**Comment by matz3** [comment]
I fully get the idea and I can imagine doing such a change for this module.
But as it requires internal changes and we (UI5) currently can't switch to a higher version because of internal dependencies, this does not have priority for us right now. I hope you can understand this.

But if you would like to file a PR, I would be happy to review it 👍

**Comment by matz3** [comment]
Closing for now. If someone has some input or would like to work on this, please let us know.
